export const WILAYAS = [
  "Adrar", "Chlef", "Laghouat", "Oum El Bouaghi", "Batna", "Béjaïa", "Biskra", "Béchar", 
  "Blida", "Bouira", "Tamanrasset", "Tébessa", "Tlemcen", "Tiaret", "Tizi Ouzou", "Alger", 
  "Djelfa", "Jijel", "Sétif", "Saïda", "Skikda", "Sidi Bel Abbès", "Anaba", "Guelma", 
  "Constantine", "Médéa", "Mostaganem", "M'Sila", "Mascara", "Ouargla", "Oran", "El Bayadh", 
  "Illizi", "Bordj Bou Arreridj", "Boumerdès", "El Tarf", "Tindouf", "Tissemsilt", "El Oued", 
  "Khenchela", "Souk Ahras", "Tipaza", "Mila", "Aïn Defla", "Naâma", "Aïn Témouchent", 
  "Ghardaïa", "Relizane", "Timimoun", "Bordj Badji Mokhtar", "Ouled Djellal", "Béni Abbès", 
  "In Salah", "In Guezzam", "Touggourt", "Djanet", "El M'Ghair", "El Meniaa"
];

export const CATEGORIES = [
  { id: "farmer", label: { ar: "فلاح", en: "Farmer", fr: "Agriculteur" } },
  { id: "breeder", label: { ar: "مربي", en: "Breeder", fr: "Éleveur" } },
  { id: "seller", label: { ar: "بائع", en: "Seller", fr: "Vendeur" } },
  { id: "specialist", label: { ar: "مختص فلاحي", en: "Agri Specialist", fr: "Spécialiste Agricole" } },
  { id: "vet", label: { ar: "مختص بيطري", en: "Vet Specialist", fr: "Spécialiste Vétérinaire" } },
];

export type Language = "ar" | "en" | "fr";

export const TRANSLATIONS = {
  ar: {
    slogan: "كل ما يحتاجه الفلاح",
    welcome: "مرحباً بك في AGROLIFE",
    login: "تسجيل الدخول",
    signup: "حساب جديد",
    email: "البريد الإلكتروني",
    phone: "رقم الهاتف",
    password: "كلمة السر",
    forgotPass: "نسيت كلمة السر؟",
    fullName: "الاسم الكامل",
    username: "اسم المستخدم",
    birthdate: "تاريخ الميلاد",
    gender: "الجنس",
    male: "ذكر",
    female: "أنثى",
    wilaya: "الولاية",
    commune: "البلدية",
    category: "الفئة",
    confirmPass: "تأكيد كلمة السر",
    verifyEmail: "تأكيد الحساب",
    verifyCodeSent: "تم إرسال رمز التأكيد إلى بريدك الإلكتروني",
    verify: "تأكيد",
    home: "الرئيسية",
    search: "بحث",
    notifications: "الإشعارات",
    messages: "الرسائل",
    profile: "الملف الشخصي",
    settings: "الإعدادات",
    favorites: "المفضلات",
    aiChat: "دردشة ذكية",
    follow: "متابعة",
    followers: "متابعون",
    following: "يتابع",
    stores: "المتاجر",
    experts: "المختصين",
    weather: "الطقس",
    consultations: "الاستشارات",
    booking: "حجز موعد",
    agriConsult: "استشارة فلاحية",
    vetConsult: "استشارة بيطرية",
    tips: "نصائح ذكية",
    forecast: "توقعات 7 أيام",
    wind: "الرياح",
    rain: "الأمطار",
    temp: "الحرارة",
    recommendation: "توصية",
    sprayNotAdvised: "لا ينصح بالرش اليوم بسبب الرياح",
    sprayAdvised: "الظروف مناسبة للرش اليوم",
    today: "اليوم",
    specialty: "التخصص",
    rating: "التقييم",
    availability: "التوفر",
    bookNow: "احجز الآن",
    history: "السجل",
    preferences: "التفضيلات",
    crops: "المحاصيل",
    livestock: "المواشي",
    googleLogin: "التسجيل عبر جوجل",
  },
  en: {
    slogan: "Everything a farmer needs",
    welcome: "Welcome to AGROLIFE",
    login: "Login",
    signup: "Sign Up",
    email: "Email",
    phone: "Phone Number",
    password: "Password",
    forgotPass: "Forgot Password?",
    fullName: "Full Name",
    username: "Username",
    birthdate: "Birth Date",
    gender: "Gender",
    male: "Male",
    female: "Female",
    wilaya: "State (Wilaya)",
    commune: "City (Commune)",
    category: "Category",
    confirmPass: "Confirm Password",
    verifyEmail: "Verify Email",
    verifyCodeSent: "A verification code has been sent to your email",
    verify: "Verify",
    home: "Home",
    search: "Search",
    notifications: "Notifications",
    messages: "Messages",
    profile: "Profile",
    settings: "Settings",
    favorites: "Favorites",
    aiChat: "AI Chat",
    follow: "Follow",
    followers: "Followers",
    following: "Following",
    stores: "Stores",
    experts: "Experts",
    weather: "Weather",
    consultations: "Consultations",
    booking: "Booking",
    agriConsult: "Agri Consult",
    vetConsult: "Vet Consult",
    tips: "Smart Tips",
    forecast: "7-Day Forecast",
    wind: "Wind",
    rain: "Rain",
    temp: "Temp",
    recommendation: "Recommendation",
    sprayNotAdvised: "Spraying not advised today due to wind",
    sprayAdvised: "Conditions are good for spraying today",
    today: "Today",
    specialty: "Specialty",
    rating: "Rating",
    availability: "Availability",
    bookNow: "Book Now",
    history: "History",
    preferences: "Preferences",
    crops: "Crops",
    livestock: "Livestock",
    googleLogin: "Sign in with Google",
  },
  fr: {
    slogan: "Tout ce dont un agriculteur a besoin",
    welcome: "Bienvenue sur AGROLIFE",
    login: "Connexion",
    signup: "Inscription",
    email: "Email",
    phone: "Numéro de téléphone",
    password: "Mot de passe",
    forgotPass: "Mot de passe oublié?",
    fullName: "Nom complet",
    username: "Nom d'utilisateur",
    birthdate: "Date de naissance",
    gender: "Genre",
    male: "Masculin",
    female: "Féminin",
    wilaya: "Wilaya",
    commune: "Commune",
    category: "Catégorie",
    confirmPass: "Confirmer le mot de passe",
    verifyEmail: "Vérifier l'Email",
    verifyCodeSent: "Un code de vérification a été envoyé à votre email",
    verify: "Vérifier",
    home: "Accueil",
    search: "Recherche",
    notifications: "Notifications",
    messages: "Messages",
    profile: "Profil",
    settings: "Paramètres",
    favorites: "Favoris",
    aiChat: "Chat IA",
    follow: "Suivre",
    followers: "Abonnés",
    following: "Abonnements",
    stores: "Magasins",
    experts: "Experts",
    weather: "Météo",
    consultations: "Consultations",
    booking: "Réservation",
    agriConsult: "Consultation Agricole",
    vetConsult: "Consultation Vétérinaire",
    tips: "Conseils",
    forecast: "Prévision 7 jours",
    wind: "Vent",
    rain: "Pluie",
    temp: "Temp",
    recommendation: "Recommandation",
    sprayNotAdvised: "Pulvérisation non conseillée aujourd'hui",
    sprayAdvised: "Conditions idéales pour pulvériser",
    today: "Aujourd'hui",
    specialty: "Spécialité",
    rating: "Évaluation",
    availability: "Disponibilité",
    bookNow: "Réserver",
    history: "Historique",
    preferences: "Préférences",
    crops: "Cultures",
    livestock: "Bétail",
    googleLogin: "Se connecter avec Google",
  }
};
